name: nonstopcoding

version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nonstopcoding_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nonstopcoding_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # RabbitMQ để quản lý bất đồng bộ
  rabbitmq:
    build: 
      context: ./backend
      dockerfile: Dockerfile.rabbitmq
    container_name: nonstopcoding_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Profile "full" dành cho khi cần test các tính năng nặng như Online Judge
  judge0:
    image: judge0/judge0:1.13.0
    container_name: nonstopcoding_judge0
    ports:
      - "2358:2358"
    profiles: ["full"]
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
