TRUNCATE TABLE public.problem_testcases CASCADE;
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (1, 990, '4\n2 7 11 15\n9', '0 1', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (2, 990, '3\n3 2 4\n6', '1 2', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (3, 991, '121', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (4, 991, '-121', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (5, 992, '3\nflower flow flight', 'fl', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (6, 992, '3\ndog racecar car', '', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (7, 993, '()[]{}', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (8, 993, '([)]', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (9, 994, '3\n1 2 4\n3\n1 3 4', '1 1 2 3 4 4', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (10, 994, '0\n\n0\n', '', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (11, 1001, 'hello', 'olleh', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (12, 1001, 'Hannah', 'hannaH', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (13, 1002, '3', '1\n2\nFizz', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (14, 1002, '5', '1\n2\nFizz\n4\nBuzz', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (15, 1003, 'aba', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (16, 1003, 'abc', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (17, 1004, 'anagram nagaram', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (18, 1004, 'rat car', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (19, 1005, '3\n2 2 1', '1', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (20, 1005, '5\n4 1 2 1 2', '4', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (21, 1006, '3\n3 2 3', '3', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (22, 1006, '7\n2 2 1 1 1 2 2', '2', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (23, 1007, '5\n0 1 0 3 12', '1 3 12 0 0', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (24, 1007, '2\n0 0', '0 0', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (25, 1008, '4\n1 2 3 1', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (26, 1008, '4\n1 2 3 4', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (27, 1009, '3\n3 0 1', '2', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (28, 1009, '2\n0 1', '2', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (29, 1010, '4\n1 2 2 1\n2\n2 2', '2', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (30, 1010, '3\n4 9 5\n5\n9 4 9 8 4', '9 4', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (31, 1011, '16', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (32, 1011, '3', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (33, 1012, 'hello', 'holle', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (34, 1012, 'leetcode', 'leotcede', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (35, 1013, 'abc ahbgdc', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (36, 1013, 'axc ahbgdc', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (37, 1014, 'leetcode', '0', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (38, 1014, 'loveleetcode', '2', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (39, 1015, '8\n4 3 2 7 8 2 3 1', '5 6', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (40, 1015, '2\n1 1', '2', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (41, 1016, '2', '1', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (42, 1016, '4', '3', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (43, 1017, '4', '4', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (44, 1017, '25', '1389537', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (45, 1018, '2', '2', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (46, 1018, '3', '3', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (47, 1019, '3\n10 15 20', '15', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (48, 1019, '10\n1 100 1 1 1 100 1 1 100 1', '6', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (49, 1020, '4\n1 2 3 1', '4', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (50, 1020, '5\n2 7 9 3 1', '12', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (51, 1021, '6\n7 1 5 3 6 4', '5', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (52, 1021, '5\n7 6 4 3 1', '0', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (53, 1022, '9\n-2 1 -3 4 -1 2 1 -5 4', '6', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (54, 1022, '1\n1', '1', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (55, 1023, '3\n1 2 3\n3\n2 5 6', '1 2 2 3 5 6', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (56, 1023, '1\n1\n0', '1', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (57, 1024, '3\n1 1 2', '2', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (58, 1024, '10\n0 0 1 1 1 2 2 3 3 4', '5', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (59, 1025, '4\n3 2 2 3\n3', '2', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (60, 1025, '8\n0 1 2 2 3 0 4 2\n2', '5', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (61, 1026, '4\n1 3 5 6\n5', '2', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (62, 1026, '4\n1 3 5 6\n2', '1', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (63, 1027, 'Hello World', '5', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (64, 1027, '   fly me   to   the moon  ', '4', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (65, 1028, '3\n1 2 3', '1 2 4', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (66, 1028, '1\n9', '1 0', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (67, 1029, '11 1', '100', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (68, 1029, '1010 1011', '10101', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (69, 1030, '4', '2', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (70, 1030, '8', '2', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (71, 1031, '19', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (72, 1031, '2', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (73, 1032, '1', 'A', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (74, 1032, '28', 'AB', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (75, 1033, 'A', '1', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (76, 1033, 'AB', '28', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (77, 1034, '27', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (78, 1034, '0', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (79, 1035, '16', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (80, 1035, '5', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (81, 1036, '16', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (82, 1036, '14', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (83, 1037, '3\n3 2 1', '1', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (84, 1037, '2\n1 2', '2', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (85, 1038, '3\n1 2 3\n2\n1 1', '1', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (86, 1038, '2\n1 2\n3\n1 2 3', '2', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (87, 1039, '6\n1 1 0 1 1 1', '3', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (88, 1039, '5\n1 0 1 1 0', '2', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (89, 1040, 'USA', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (90, 1040, 'FlaG', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (91, 1041, '100', '202', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (92, 1041, '-7', '-10', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (93, 1042, '5\n5 4 3 2 1', 'Gold Medal Silver Medal Bronze Medal 4 5', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (94, 1042, '1\n10', 'Gold Medal', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (95, 1043, '28', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (96, 1043, '7', 'false', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (97, 1044, '4\nHello Alaska Dad Peace', 'Alaska Dad', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (98, 1044, '2\nomk adsdf', 'adsdf', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (99, 1045, '4\n1 2 2 3', '2', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (100, 1045, '3\n1 1 2', '1', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (101, 1046, '4\n4 2 1 3', '1 2,2 3,3 4', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (102, 1046, '4\n1 3 6 10', '1 3', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (103, 1047, 'Let''s take LeetCode contest', 's''teL ekat edoCteeL tsetnoc', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (104, 1047, 'Mr Ding', 'rM gniD', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (105, 1048, '4\n1 4 3 2', '4', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (106, 1048, '6\n6 2 6 5 1 2', '9', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (107, 1049, 'aba', 'true', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (108, 1049, 'abca', 'true', 2, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (109, 1050, '6\n1 1 2 2 3 3', '3', 1, NULL);
INSERT INTO public.problem_testcases (id, problem_id, input_data, expected_output, order_index, token) VALUES (110, 1050, '4\n1 1 2 3', '2', 2, NULL);
SELECT setval('public.problem_testcases_id_seq', 110);
UPDATE public.problems p SET total_testcase = (SELECT COUNT(*) FROM public.problem_testcases pt WHERE pt.problem_id = p.id);